package com.classmode.presentation.theme

import androidx.compose.ui.graphics.Color

// Premium Light Palette
val PrimaryLight = Color(0xFF195FA7)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFD3E4FF)
val OnPrimaryContainerLight = Color(0xFF001C38)
val SecondaryLight = Color(0xFF555F71)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFD9E3F8)
val OnSecondaryContainerLight = Color(0xFF121C2B)
val TertiaryLight = Color(0xFF6E5676)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFF7D8FF)
val OnTertiaryContainerLight = Color(0xFF271330)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFDFBFF)
val OnBackgroundLight = Color(0xFF1A1C1E)
val SurfaceLight = Color(0xFFFDFBFF)
val OnSurfaceLight = Color(0xFF1A1C1E)
val SurfaceVariantLight = Color(0xFFDFE2EB)
val OnSurfaceVariantLight = Color(0xFF43474E)
val OutlineLight = Color(0xFF74777F)

// Premium Dark Palette
val PrimaryDark = Color(0xFFA2C9FF)
val OnPrimaryDark = Color(0xFF00315C)
val PrimaryContainerDark = Color(0xFF004882)
val OnPrimaryContainerDark = Color(0xFFD3E4FF)
val SecondaryDark = Color(0xFFBDC7DC)
val OnSecondaryDark = Color(0xFF273141)
val SecondaryContainerDark = Color(0xFF3D4758)
val OnSecondaryContainerDark = Color(0xFFD9E3F8)
val TertiaryDark = Color(0xFFDABCE2)
val OnTertiaryDark = Color(0xFF3E2846)
val TertiaryContainerDark = Color(0xFF553F5D)
val OnTertiaryContainerDark = Color(0xFFF7D8FF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF1A1C1E)
val OnBackgroundDark = Color(0xFFE3E2E6)
val SurfaceDark = Color(0xFF1A1C1E)
val OnSurfaceDark = Color(0xFFE3E2E6)
val SurfaceVariantDark = Color(0xFF43474E)
val OnSurfaceVariantDark = Color(0xFFC3C6CF)
val OutlineDark = Color(0xFF8D9199)
